version: '3.9'

services:
  db: 
    image: mysql:latest
    container_name: mysql_database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yhayatytech20022021
      MYSQL_DATABASE: test
    ports:
      - 3306:3306

  phpmyadmin: 
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80